#!/bin/zsh

usage () {
    echo "Don't run this script directly, instead type '. goactivate'.

Script to set PATH, GOPATH and shell prompt for your project. Drop this script
in your PATH. To activate environment, go in the root directory of the project
and type:

  . goactivate

This will set PATH to:

  /project/home/bin:\$PATH

And it will also set GOPATH to:

  /project/home

So that dependencies will be installed in your project home directory.
Furthermore, the shell prompt is modified so that it will show activated
project between brackets.

To deactivate the environment, type:

  deactivate

This will restore your previous PATH, GOPATH and shell prompt."
}

[[ $ZSH_EVAL_CONTEXT == :file$ ]] && usage

deactivate () {
    # reset old environment variables
    if [ -n "$_OLD_VIRTUAL_PATH" ] ; then
        PATH="$_OLD_VIRTUAL_PATH"
        export PATH
        unset _OLD_VIRTUAL_PATH
    fi
    if [ -n "$_OLD_VIRTUAL_GOPATH" ] ; then
        GOPATH="$_OLD_VIRTUAL_GOPATH"
        export GOPATH
        unset _OLD_VIRTUAL_GOPATH
    fi

    if [ -n "$_OLD_VIRTUAL_PS1" ] ; then
        PS1="$_OLD_VIRTUAL_PS1"
        export PS1
        unset _OLD_VIRTUAL_PS1
    fi

    unset VIRTUAL_ENV
    if [ ! "$1" = "nondestructive" ] ; then
    # Self destruct!
        unset -f deactivate
    fi
}

# unset irrelevant variables
deactivate nondestructive

VIRTUAL_ENV=`pwd`
export VIRTUAL_ENV

_OLD_VIRTUAL_PATH="$PATH"
PATH="$VIRTUAL_ENV/bin:$PATH"
export PATH

_OLD_VIRTUAL_GOPATH="$GOPATH"
GOPATH="$VIRTUAL_ENV"
export GOPATH

if [ -z "$VIRTUAL_ENV_DISABLE_PROMPT" ] ; then
    _OLD_VIRTUAL_PS1="$PS1"
    if [ "x" != x ] ; then
        PS1="$PS1"
    else
    if [ "`basename \"$VIRTUAL_ENV\"`" = "__" ] ; then
        # special case for Aspen magic directories
        # see http://www.zetadev.com/software/aspen/
        PS1="[GoProject:`basename \`dirname \"$VIRTUAL_ENV\"\``] $PS1"
    else
        PS1="[GoProject:`basename \"$VIRTUAL_ENV\"`]$PS1"
    fi
    fi
    export PS1
fi
